services:
  summarizer:
    image: jeffreylu0/summarizer
    build: .
    ports:
      - "8000:8000"
    environment:
      - KMP_DUPLICATE_LIB_OK=True
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./models
        target: /usr/code/models